name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Cache built site
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: site
          restore-keys: |
            mkdocs-material-site-

      - name: Build and Deploy using MkDocs
        run: |
          docker run --rm \
            -v $(pwd):/docs \
            cloaks/mkdocs:latest \
            gh-deploy --force
